<a href="https://colab.research.google.com/github/couleux/MATRIX/blob/main/Matrix_Unary_Computations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
transpose_A = matrix_A.T
print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric? ", is_symmetric)


Is Matrix A symmetric?  False


In [ ]:
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)

Random Matrix:
 [[9 8 3 2]
 [9 5 6 3]
 [8 4 8 4]
 [8 2 7 3]]

Is the random matrix symmetric?  False


In [ ]:
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)



Trace of Matrix A: 15


In [ ]:
identity_matrix = np.identity(5)
trace_identity = np.trace(identity_matrix)
print("\nTrace of 5x5 Identity Matrix:", trace_identity)



Trace of 5x5 Identity Matrix: 5.0


In [ ]:
det_A = np.linalg.det(matrix_A)
print("\nDeterminant of Matrix A:", det_A)


Determinant of Matrix A: 0.0


In [ ]:
matrix_C = np.array([[4, 6], [3, 8]])
det_C = (matrix_C[0, 0] * matrix_C[1, 1]) - (matrix_C[0, 1] * matrix_C[1, 0])
print("\nDeterminant of Matrix C:", det_C)



Determinant of Matrix C: 14


In [ ]:
matrix_B = np.array([[2, 4, 3],
                     [1, 5, 7],
                     [6, 8, 9]])
det_B = np.linalg.det(matrix_B)
print("\nDeterminant of Matrix B:", det_B)


Determinant of Matrix B: 44.000000000000014


In [ ]:
random_matrix_3x3 = np.random.randint(1, 10, (3, 3))
transpose_3x3 = random_matrix_3x3.T
det_random_3x3 = np.linalg.det(random_matrix_3x3)
print("\nRandom 3x3 Matrix:\n", random_matrix_3x3)
print("\nTranspose of Random 3x3 Matrix:\n", transpose_3x3)
print("\nDeterminant of Random 3x3 Matrix:", det_random_3x3)


Random 3x3 Matrix:
 [[7 9 7]
 [6 1 7]
 [4 9 7]]

Transpose of Random 3x3 Matrix:
 [[7 6 4]
 [9 1 9]
 [7 7 7]]

Determinant of Random 3x3 Matrix: -167.99999999999997


In [ ]:
symmetric_matrix = np.array([[2, 1, 1],
                              [1, 2, 1],
                              [1, 1, 2]])
is_symmetric_matrix = (symmetric_matrix == symmetric_matrix.T).all()
print("\nSymmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric? ", is_symmetric_matrix)


Symmetric Matrix:
 [[2 1 1]
 [1 2 1]
 [1 1 2]]

Is the matrix symmetric?  True
