<a href="https://colab.research.google.com/github/couleux/MATRIX/blob/main/Silva_AdvancedMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Exercise 1: Matrix Addition & Subtraction**

In [ ]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])


result_addition = matrix_a + matrix_b
print("Addition Result:")
print(result_addition)


result_subtraction = matrix_a - matrix_b
print("\nSubtraction Result:")
print(result_subtraction)

Addition Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


### **Exercise 2: Matrix Multiplication**



In [ ]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [10, 12]])

result_multiplication = np.matmul(matrix_a, matrix_b)
print("Matrix Multiplication Result:")
print(result_multiplication)

Matrix Multiplication Result:
[[ 55  64]
 [133 154]]


### **Exercise 3: Matrix Transpose**

In [ ]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])

matrix_transpose = np.transpose(matrix_a)

print("\nTranspose of the Matrix:")
print(matrix_transpose)


Transpose of the Matrix:
[[1 4]
 [2 5]
 [3 6]]


### **Exercise 4: Calculating the Determinant**



In [ ]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

determinant = np.linalg.det(matrix_a)

print("Determinant of the Matrix:")
print(determinant)

Determinant of the Matrix:
0.0


### **Exercise 5: Finding the Inverse**

In [ ]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

inverse = np.linalg.inv(matrix_a)

print("Inverse of the Matrix:")
print(inverse)

Inverse of the Matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
