<a href="https://colab.research.google.com/github/couleux/MATRIX/blob/main/Solving_Rank_and_Systems_of_Equations_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define the matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the rank
rank = np.linalg.matrix_rank(A)

print(f"Rank of matrix A: {rank}")


Rank of matrix A: 2


In [ ]:
import numpy as np

# Coefficient matrix
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Constant vector
b = np.array([8, -11, -3])

# Solve the system
if np.linalg.det(A) != 0:  # Check if the matrix is invertible
    x = np.linalg.inv(A).dot(b)
    print(f"Solution: {x}")
else:
    print("Matrix A is not invertible. No unique solution.")


Solution: [ 2.  3. -1.]


In [ ]:
import numpy as np

# Define two matrices of size 4x4
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = np.array([[16, 15, 14, 13],
              [12, 11, 10, 9],
              [8, 7, 6, 5],
              [4, 3, 2, 1]])

# Add the matrices
C = A + B

print("Sum of A and B:")
print(C)


Sum of A and B:
[[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]]
